//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envz.Common.UI.Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Envz.Common.UI.Loc.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add application.
        /// </summary>
        public static string AddApplication_Title {
            get {
                return ResourceManager.GetString("AddApplication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application has been added yet.
        /// </summary>
        public static string CreateEnvironment_NoApplications {
            get {
                return ResourceManager.GetString("CreateEnvironment_NoApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create environment.
        /// </summary>
        public static string CreateEnvironment_Title {
            get {
                return ResourceManager.GetString("CreateEnvironment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit environment.
        /// </summary>
        public static string EditEnvironment_Title {
            get {
                return ResourceManager.GetString("EditEnvironment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Global_Add {
            get {
                return ResourceManager.GetString("Global_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Global_Applications {
            get {
                return ResourceManager.GetString("Global_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Global_Browse {
            get {
                return ResourceManager.GetString("Global_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Global_Create {
            get {
                return ResourceManager.GetString("Global_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environments.
        /// </summary>
        public static string Global_Environments {
            get {
                return ResourceManager.GetString("Global_Environments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Global_Home {
            get {
                return ResourceManager.GetString("Global_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Global_Icon {
            get {
                return ResourceManager.GetString("Global_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Global_Language {
            get {
                return ResourceManager.GetString("Global_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Global_Name {
            get {
                return ResourceManager.GetString("Global_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Global_Path {
            get {
                return ResourceManager.GetString("Global_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Global_Select {
            get {
                return ResourceManager.GetString("Global_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Global_Settings {
            get {
                return ResourceManager.GetString("Global_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeApplications_Title {
            get {
                return ResourceManager.GetString("HomeApplications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeEnvironments_Title {
            get {
                return ResourceManager.GetString("HomeEnvironments_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application &quot;{0}&quot; could not be created because an application with this name already exists..
        /// </summary>
        public static string KnownError_CreateApplicationAlreadyExists {
            get {
                return ResourceManager.GetString("KnownError_CreateApplicationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment could not be created because the application &quot;{0}&quot; was not found..
        /// </summary>
        public static string KnownError_CreateEnvironmentApplicationNotFound {
            get {
                return ResourceManager.GetString("KnownError_CreateEnvironmentApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment could not be created because its name is empty..
        /// </summary>
        public static string KnownError_CreateEnvironmentInvalidEnvironmentName {
            get {
                return ResourceManager.GetString("KnownError_CreateEnvironmentInvalidEnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application &quot;{0}&quot; could not be deleted because it was not found..
        /// </summary>
        public static string KnownError_DeleteApplicationNotFound {
            get {
                return ResourceManager.GetString("KnownError_DeleteApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application &quot;{0}&quot; could not be deleted because it is still used by an environment..
        /// </summary>
        public static string KnownError_DeleteApplicationStillUsed {
            get {
                return ResourceManager.GetString("KnownError_DeleteApplicationStillUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible operation.
        /// </summary>
        public static string KnownError_Title {
            get {
                return ResourceManager.GetString("KnownError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an application.
        /// </summary>
        public static string SelectApplication_Title {
            get {
                return ResourceManager.GetString("SelectApplication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        public static string UnknownError_Message {
            get {
                return ResourceManager.GetString("UnknownError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error.
        /// </summary>
        public static string UnknownError_Title {
            get {
                return ResourceManager.GetString("UnknownError_Title", resourceCulture);
            }
        }
    }
}
