<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="UI\Assets\Fonts\Poppins-Bold.ttf" />
    <Resource Include="UI\Assets\Fonts\Poppins-Medium.ttf" />
    <Resource Include="UI\Assets\Fonts\Poppins-Regular.ttf" />
    <Resource Include="UI\Assets\Fonts\Poppins-SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="UI\Dialogs\Confirm\ConfirmDialog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="UI\Dialogs\Error\ErrorDialog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="UI\Loc\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="UI\Loc\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
